# Generated by Django 4.2.11 on 2026-03-16 00:48

import apps.tours.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under review'), ('live', 'Live'), ('paused', 'Paused'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('category', models.CharField(choices=[('Trekking', 'Trekking'), ('Culture', 'Culture'), ('Wildlife', 'Wildlife'), ('Adventure', 'Adventure'), ('Food & Wine', 'Food & Wine'), ('Cycling', 'Cycling'), ('Water Sports', 'Water Sports'), ('Winter Sports', 'Winter Sports'), ('Wellness', 'Wellness'), ('Other', 'Other')], db_index=True, default='Trekking', max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Challenging', 'Challenging'), ('Expert', 'Expert')], default='Moderate', max_length=12)),
                ('tour_type', models.CharField(choices=[('multi', 'Multi-day (fixed departures)'), ('single', 'Single-day (any date)')], default='multi', max_length=8)),
                ('country', models.CharField(db_index=True, max_length=80)),
                ('destination', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('days', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_child', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to default to 85% of adult price', max_digits=10, null=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('max_group', models.PositiveSmallIntegerField(default=12)),
                ('min_group', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, help_text='HTML allowed (rich text)')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='List of short highlight strings')),
                ('includes', models.JSONField(blank=True, default=list)),
                ('excludes', models.JSONField(blank=True, default=list)),
                ('requirements', models.TextField(blank=True)),
                ('meeting_point', models.TextField(blank=True)),
                ('end_point', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, default='🌍', max_length=8)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Short keyword tags')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.tours.models.tour_photo_path)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='0 = hero image')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tours.tour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TourFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='tours.tour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StayBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=160)),
                ('property_type', models.CharField(blank=True, choices=[('Hotel', 'Hotel'), ('Hostel', 'Hostel'), ('Guesthouse', 'Guesthouse'), ('Camping/glamping', 'Camping / glamping'), ('Homestay', 'Homestay'), ('Mountain hut', 'Mountain hut'), ('Other', 'Other')], max_length=20)),
                ('comfort_level', models.CharField(blank=True, choices=[('Budget', 'Budget'), ('Standard', 'Standard'), ('Superior', 'Superior'), ('Luxury', 'Luxury')], max_length=10)),
                ('night_from', models.PositiveSmallIntegerField(help_text='First night covered (1-indexed)')),
                ('night_to', models.PositiveSmallIntegerField(help_text='Last night covered')),
                ('room_types', models.JSONField(blank=True, default=list, help_text='List of {name, price_supplement} dicts')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='tours.tour')),
            ],
            options={
                'ordering': ['night_from'],
            },
        ),
        migrations.CreateModel(
            name='SavedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tours.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartureDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField()),
                ('spots_total', models.PositiveSmallIntegerField()),
                ('spots_left', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('guaranteed', 'Guaranteed'), ('full', 'Full'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use tour base price', max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tours.tour')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='DayItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('meals', models.CharField(blank=True, help_text='e.g. Breakfast, Dinner', max_length=80)),
                ('elevation', models.CharField(blank=True, help_text='e.g. +600m / -200m', max_length=40)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tours.tour')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='CancelPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_min', models.PositiveSmallIntegerField(help_text='Days before departure (lower bound)')),
                ('days_before_max', models.PositiveSmallIntegerField(blank=True, help_text='Days before departure (upper bound, null = ∞)', null=True)),
                ('penalty_pct', models.PositiveSmallIntegerField(default=0, help_text='Percentage of total price charged as penalty (0 = full refund)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('label', models.CharField(blank=True, help_text='e.g. "Full refund", "50% penalty"', max_length=80)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_policy', to='tours.tour')),
            ],
            options={
                'ordering': ['-days_before_max'],
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['status', 'category'], name='tours_tour_status_aa27ed_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['country', 'status'], name='tours_tour_country_13ec99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedtour',
            unique_together={('user', 'tour')},
        ),
        migrations.AlterUniqueTogether(
            name='departuredate',
            unique_together={('tour', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='dayitinerary',
            unique_together={('tour', 'day_number')},
        ),
    ]
