# Generated by Django 4.2.11 on 2026-03-29 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'role': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stayblock',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='savedtour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='savedtour',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tours.stayblock'),
        ),
        migrations.AddField(
            model_name='departuredate',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='cancelperiod',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_policy', to='tours.tour'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlistentry',
            unique_together={('tour', 'email', 'departure_label')},
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['status', 'category'], name='tours_tour_status_aa27ed_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['country', 'status'], name='tours_tour_country_13ec99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedtour',
            unique_together={('tourist', 'tour')},
        ),
        migrations.AlterUniqueTogether(
            name='departuredate',
            unique_together={('tour', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='dayitinerary',
            unique_together={('tour', 'day_number')},
        ),
    ]
