# Generated by Django 4.2.11 on 2026-06-15 17:40

import apps.tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.tour_thumb_path),
        ),
    ]
