# Generated by Django 4.2.11 on 2026-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourphoto_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
