# Generated by Django 4.2.11 on 2026-08-15 18:37

import apps.tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tour_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourphoto',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.tour_photo_path),
        ),
        migrations.AddField(
            model_name='tourphoto',
            name='thumbnail_webp',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.tour_thumb_path),
        ),
    ]
