# Generated by Django 4.2.11 on 2026-03-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_review_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='difficulty_note',
            field=models.CharField(blank=True, default='', help_text='Operator note on physical demands', max_length=300),
        ),
        migrations.AddField(
            model_name='tour',
            name='extras',
            field=models.JSONField(blank=True, default=list, help_text='Optional add-ons: [{name, description, price_per_person}]'),
        ),
        migrations.AddField(
            model_name='tour',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Multi-select language list e.g. ["English","Russian"]'),
        ),
    ]
