# Generated by Django 4.2.11 on 2026-03-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_add_languages_difficulty_note_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='meeting_time',
            field=models.CharField(blank=True, default='', help_text='Daily meet-up time e.g. "09:00 AM"', max_length=20),
        ),
    ]
