# Generated by Django 4.2.11 on 2026-03-22 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_add_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='balance_due_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Days before departure when balance payment is due'),
        ),
        migrations.AddField(
            model_name='tour',
            name='deposit_pct',
            field=models.PositiveSmallIntegerField(default=30, help_text='Deposit percentage required at booking (0–100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
