# Generated by Django 4.2.11 on 2026-03-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tour_balance_due_days_tour_deposit_pct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
