# Generated by Django 4.2.11 on 2026-03-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_remove_legacy_review_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='timezone',
            field=models.CharField(blank=True, default='Europe/Moscow', help_text='IANA timezone for departure city (used for cancel/deposit deadlines)', max_length=50),
        ),
    ]
