# Generated by Django 4.2.11 on 2026-03-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_add_timezone_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Short keyword tags', null=True),
        ),
    ]
