# Generated by Django 4.2.11 on 2026-03-27 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_tags_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='tours.departuredate'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
