# Generated by Django 4.2.11 on 2026-03-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_waitlist_departure_fk_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='change_cancel_window_until',
            field=models.DateTimeField(blank=True, help_text='Tourists may cancel penalty-free until this datetime after a material change.', null=True),
        ),
    ]
