# Generated by Django 4.2.11 on 2026-03-29 19:35

import apps.bookings.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.bookings.models.booking_ref, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=12)),
                ('adults', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('infants', models.PositiveSmallIntegerField(default=0)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('emergency_name', models.CharField(blank=True, max_length=120)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('room_preference', models.CharField(blank=True, help_text='Room type selected at booking time', max_length=120)),
                ('selected_extras', models.TextField(blank=True, help_text='Comma-separated extra services selected at booking time')),
                ('cancel_policy_snapshot', models.JSONField(blank=True, default=list, help_text='Cancellation policy tiers snapshotted at booking time')),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_child', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost of selected add-on extras at booking time', max_digits=10)),
                ('room_supplement_cost', models.DecimalField(decimal_places=2, default=0, help_text='Room type supplement (or discount) at booking time', max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('payment_method', models.CharField(blank=True, choices=[('yookassa', 'YooKassa'), ('sbp', 'СБП'), ('bank', 'Bank transfer')], max_length=20)),
                ('yookassa_payment_id', models.CharField(blank=True, default='', help_text='YooKassa payment UUID', max_length=60)),
                ('deposit_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('balance_due_date', models.DateField(blank=True, help_text='Date balance payment is due', null=True)),
                ('balance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_payment_id', models.CharField(blank=True, default='', help_text='YooKassa payment UUID for balance', max_length=64)),
                ('balance_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Refund amount in tour currency', max_digits=10)),
                ('refund_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('issued', 'Issued'), ('manual', 'Manual transfer')], default='none', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_balance_reminder_sent', models.DateTimeField(blank=True, help_text='Last time an operator balance reminder was sent for this booking', null=True)),
                ('cooling_off_until', models.DateTimeField(blank=True, help_text='Penalty-free cancel deadline set at booking creation. +30 min if departure >7 days away, +15 min if ≤7 days. Takes precedence over all cancellation policy rules.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_from', models.DateField(blank=True, null=True)),
                ('preferred_to', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=2)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('infants', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('read_by_operator', models.BooleanField(default=False)),
                ('operator_reply', models.TextField(blank=True, default='')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_operator', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bookings.enquirymessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
