# Generated by Django 4.2.11 on 2026-03-16 00:48

import apps.bookings.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_from', models.DateField(blank=True, null=True)),
                ('preferred_to', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=2)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('infants', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('read_by_operator', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_enquiries', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='tours.tour')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.bookings.models.booking_ref, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=12)),
                ('adults', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('infants', models.PositiveSmallIntegerField(default=0)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('emergency_name', models.CharField(blank=True, max_length=120)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_child', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('payment_ref', models.CharField(blank=True, help_text='YooKassa / Stripe payment ID', max_length=120)),
                ('payment_method', models.CharField(blank=True, choices=[('yookassa', 'YooKassa'), ('stripe', 'Stripe'), ('bank', 'Bank transfer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tours.departuredate')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tours.tour')),
                ('tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tour', 'status'], name='bookings_bo_tour_id_b6c4af_idx'), models.Index(fields=['tourist', 'status'], name='bookings_bo_tourist_e38522_idx')],
            },
        ),
    ]
