# Generated by Django 4.2.11 on 2026-03-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_enquiry_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_ref',
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_due_date',
            field=models.DateField(blank=True, help_text='Date balance payment is due', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, default='', help_text='YooKassa payment UUID', max_length=60),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('yookassa', 'YooKassa'), ('sbp', 'СБП'), ('bank', 'Bank transfer')], max_length=20),
        ),
    ]
