# Generated by Django 4.2.11 on 2026-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
