# Generated by Django 4.2.11 on 2026-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe (card)'), ('paypal', 'PayPal'), ('yookassa', 'YooKassa'), ('sbp', 'СБП'), ('bank', 'Bank transfer')], max_length=20),
        ),
    ]
