# Generated by Django 4.2.11 on 2026-03-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_enquiryreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_preference',
            field=models.CharField(blank=True, help_text='Room type selected at booking time', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_extras',
            field=models.TextField(blank=True, help_text='Comma-separated extra services selected at booking time'),
        ),
    ]
