# Generated by Django 4.2.11 on 2026-08-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform commission % agreed at the time this booking was paid', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_reference',
            field=models.CharField(blank=True, default='', help_text='Bank transfer reference, so a guide asking "was I paid?" has an answer', max_length=80),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_status',
            field=models.CharField(choices=[('not_due', 'Not due yet'), ('due', 'Due'), ('paid', 'Paid')], default='not_due', max_length=12),
        ),
    ]
