# Generated by Django 4.2.11 on 2026-08-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_commission_pct_booking_payout_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('tourist', 'Traveller'), ('operator', 'Guide'), ('operator_timeout', 'Guide never responded'), ('system_no_deposit', 'Unpaid, expired'), ('system_past_departure', 'Departure passed'), ('admin', 'Us')], db_index=True, default='', max_length=24),
        ),
    ]
