# Generated by Django 4.2.11 on 2026-03-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_room_preference_booking_selected_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_policy_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Cancellation policy tiers snapshotted at booking time'),
        ),
    ]
