# Generated by Django 4.2.11 on 2026-08-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', help_text='Reason given at cancellation. Kept because "we review guide cancellations" is not a policy if the reason only ever existed in an email.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_held',
            field=models.BooleanField(default=False),
        ),
    ]
