# Generated by Django 4.2.11 on 2026-08-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_cancel_reason_booking_seats_held'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cooling_off_until',
            field=models.DateTimeField(blank=True, help_text='Penalty-free cancel deadline set at booking creation. +24 h if departure is >30 days away, +2 h if 8–30 days, +30 min if ≤7 days. Takes precedence over all cancellation policy rules, including a policy the guide wrote themselves.', null=True),
        ),
    ]
