# Generated by Django 4.2.11 on 2026-03-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_refund_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_balance_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last time an operator balance reminder was sent for this booking', null=True),
        ),
    ]
