# Generated by Django 4.2.11 on 2026-08-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_cooling_off_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='capture_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='capture_grace_until',
            field=models.DateTimeField(blank=True, help_text='Set when a capture fails. Past this, the booking is cancelled and the seat released.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='capture_last_error',
            field=models.CharField(blank=True, default='', help_text='Why the last capture failed, for support to quote back.', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='capture_reminder_sent',
            field=models.BooleanField(default=False, help_text='Halfway nudge sent. Separate from capture_attempts, which moves on every retry and so cannot double as this flag.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='capture_status',
            field=models.CharField(choices=[('none', 'Charged outright'), ('authorized', 'Authorised, not yet charged'), ('captured', 'Charged'), ('failed', 'Charge failed'), ('voided', 'Authorisation released')], db_index=True, default='none', max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12),
        ),
    ]
