# Generated by Django 4.2.11 on 2026-03-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_add_last_balance_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extras_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of selected add-on extras at booking time', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_supplement_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Room type supplement (or discount) at booking time', max_digits=10),
        ),
    ]
