# Generated by Django 4.2.11 on 2026-03-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_add_extras_room_supplement_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cooling_off_until',
            field=models.DateTimeField(blank=True, help_text='Penalty-free cancel deadline set at booking creation. +30 min if departure >7 days away, +15 min if ≤7 days. Takes precedence over all cancellation policy rules.', null=True),
        ),
    ]
