# Generated by Django 4.2.11 on 2026-03-30 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payout_account',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_bank',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_bik',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_corr_account',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='doc_type',
            field=models.CharField(choices=[('identity', 'Identity document'), ('credential', 'Guide credential')], default='identity', max_length=12),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='document',
            field=models.FileField(upload_to='verification/'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
