# Generated by Django 4.2.11 on 2026-03-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationdocument_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_emails',
            field=models.BooleanField(default=False),
        ),
    ]
