# Generated by Django 4.2.11 on 2026-04-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_payout_account_user_payout_bank_user_payout_bik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.CharField(blank=True, default='', help_text='Operator: years of guiding experience (e.g. "5–10 years")', max_length=20),
        ),
    ]
