# Generated by Django 4.2.11 on 2026-03-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_marketing_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Operator Telegram chat ID for instant notifications', max_length=32),
        ),
    ]
