# Generated by Django 4.2.11 on 2026-06-15 18:40

import apps.users.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fix_social_app_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='document',
            field=models.FileField(storage=apps.users.storages.private_media_storage, upload_to='verification/'),
        ),
    ]
