# Generated by Django 4.2.11 on 2026-08-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_verificationdocument_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_pct_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the platform commission % for this guide. Leave blank for the standard rate.', max_digits=5, null=True),
        ),
    ]
