# Generated by Django 4.2.11 on 2026-08-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_commission_pct_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payout_bank_country',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_iban',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_swift',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_type',
            field=models.CharField(blank=True, choices=[('ru', 'Russian bank account'), ('intl', 'Bank account outside Russia')], default='', max_length=8),
        ),
    ]
