# Generated by Django 4.2.11 on 2026-08-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_payout_bank_country_user_payout_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='purged_at',
            field=models.DateTimeField(blank=True, help_text='When the file itself was deleted under the retention rule. The row stays so the verification decision remains on record.', null=True),
        ),
    ]
