# Generated by Django 4.2.11 on 2026-08-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_verificationdocument_purged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guide_terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When this guide accepted the Terms for Travel Experts', null=True),
        ),
    ]
