# Generated by Django 4.2.11 on 2026-08-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_guide_terms_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True, default='', help_text='Claimed, not verified — check against their uploaded documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, default='', help_text='Languages this guide says they guide in', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_link',
            field=models.CharField(blank=True, default='', help_text='Existing reviews or profile they offered as evidence', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_source',
            field=models.CharField(blank=True, default='', help_text='How they heard about us. Attribution only, never shown.', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='tour_types',
            field=models.JSONField(blank=True, default=list, help_text='Kinds of tour they said they run, at application time'),
        ),
        migrations.AddField(
            model_name='user',
            name='typical_group_size',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
