# Generated by Django 4.2.11 on 2026-08-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_certifications_user_languages_user_profile_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский')], db_index=True, default='en', help_text='Which language to write to this person in. Set from the page they signed up on, and changeable in their settings. The site has always been bilingual; the emails were not.', max_length=5),
        ),
    ]
