# Generated by Django 4.2.11 on 2026-03-18 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0005_savedtour_review_waitlistentry'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tourreview',
            name='unique_tourist_tour_review',
        ),
        migrations.RenameIndex(
            model_name='tourreview',
            new_name='reviews_tou_tour_id_4daaee_idx',
            old_name='reviews_tou_tour_id_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tourreview',
            unique_together={('tourist', 'tour')},
        ),
    ]
