# Generated by Django 4.2.11 on 2026-03-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_tourreview_unique_tourist_tour_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=10),
        ),
    ]
