# Generated by Django 4.2.11 on 2026-03-29 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreview',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tourreview',
            index=models.Index(fields=['tour', 'status'], name='reviews_tou_tour_id_4daaee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourreview',
            unique_together={('tourist', 'tour')},
        ),
    ]
